name: Schedule Data Fetching

on:
  schedule:
    - cron: "*/5 * * * *" # This cron syntax will trigger the action every 5 minutes
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  fetchData:
    runs-on: ubuntu-latest # Use Ubuntu-based virtual machine for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Checkout the code from your GitHub repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Specify the Python version to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies

      - name: Run the data fetching script
        run: |
          python script.py  # Replace with the actual name of your script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
