name: Schedule Data Fetching

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows manual trigger from the UI

jobs:
  fetchData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Use the latest stable version

      - name: Set up Python
        uses: actions/setup-python@v3 # Use the latest stable version
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the data fetching script
        run: |
          python script.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
